# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3db407418b0a1745c8a0cb692036edf9659cbf0a01386ff32e68b50e4fd5893b32c9e4479b2a14d5e8e9a51c8fdc73a14b9a72a10aff44970cf1e9ae4d6f3dc6

test:
  secret_key_base: f081d8504d2cc5960c42e8db71e6f7db98e6e93aef282565ec67e80df91bc0e4b60a13707897165755ebba85397cc4ffdb393ffcfa3f10f37b09940418971ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
